name: nodelabs
description: "Nodelabs depo app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  # State Managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5


  get_it: ^7.6.4
  injectable: ^2.3.2


  # Request tools
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1


  # local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0


  #router
  go_router: ^12.1.3

  #utils
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.4
  lottie: ^2.7.0
  intl: ^0.20.2
  google_fonts:

  # firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.7.4


  #loging
  logger: ^2.0.2+1


  # localization
  easy_localization: ^3.0.8

  dartz: ^0.10.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  mockito: ^5.4.2
  bloc_test: ^9.1.4
  mocktail: ^1.0.1
  http_mock_adapter: ^0.6.1


  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  freezed: ^2.4.6



  # Analiz araçları
  very_good_analysis:
  flutter_lints: ^5.0.0



  # launcher icon generators
  flutter_launcher_icons: ^0.14.4

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/SinFlixLogo.png"
  min_sdk_android: 21

flutter:




  uses-material-design: true


  assets:
    - assets/images/
    - assets/translations/









